//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluehill.Analyzers {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bluehill.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Classes without derived types should be sealed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No types are derived from class &apos;{0}&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classes without derived types should be sealed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fields should be at the top of the type definition.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not at the top of the type definition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fields should be at the top of the type definition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0002AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The parameters of the primary constructor must not be reassigned.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0003AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0003AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; has been reassigned과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0003AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prohibit reassignment of primary constructor parameters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0003AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0003AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() must be implemented explicitly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0004AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0004AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() is not explicitly implemented과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0004AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() must be explicitly implemented과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0004AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0004AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() must return null, and must not be abstract or throw exceptions.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0005AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0005AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() does not return null과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0005AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() must return null과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0005AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0005AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IXmlSerializable.GetSchema() should never be called.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0006AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0006AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calling IXmlSerializable.GetSchema()과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0006AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Never call IXmlSerializable.GetSchema()과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0006AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0006AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is recommended to use System.Threading.Lock instead of System.Object for locking.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0007AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0007AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use System.Threading.Lock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0007AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prefer System.Threading.Lock over System.Object과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0007AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0007AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The negated pattern should not be used repeatedly.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0008AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0008AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use &apos;not&apos; only once or not at all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0008AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t repeat negative patterns과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0008AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0008AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integers and Decimal should never be divided by the constant 0. This may cause a DividedByZeroException.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0009AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0009AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dividing by constant 0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0009AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Integers and Decimal should never be divided by the constant 0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0009AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0009AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When comparing Span and a constant, you should use pattern matching instead of the equality/inequality operators, unless you want to compare what the addresses of the objects pointed to.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0010AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0010AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unless you want to compare the address of the pointed object, use pattern matching instead과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0010AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0010AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use pattern matching when comparing Span and a constant과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0010AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0010AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When comparing Span and a non-constant, you should use SequenceEqual method instead of the equality/inequality operators, unless you want to directly compare what the addresses of the objects pointed to.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0011AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0011AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unless you want to compare the address of the pointed object, use SequenceEqual method instead과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0011AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0011AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use SequenceEqual when comparing Span and a non-constant과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0011AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0011AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should not conflict with primary constructor parameters.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0012AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0012AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name &apos;{0}&apos; conflicts one of the primary constructor parameters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0012AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0012AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field names should not conflict with primary constructor parameters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0012AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0012AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can make this lambda static.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0013AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0013AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lambda can be made static과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0013AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0013AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A lambda can be made static과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0013AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0013AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This enumeration has extension methods ToStringFast() or HasFlagFast(). For performance and AOT compatibility, you should use those extension methods instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0014AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0014AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use &apos;{0}&apos; method과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0014AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0014AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use ToStringFast() or HasFlagFast()과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0014AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0014AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This enumeration does not have the Bluehill.EnumExtensionsAttribute, but calls the ToString() or HasFlag() methods. For performance and AOT compatibility, you should apply the Bluehill.EnumExtensionsAttribute and use the ToStringFast() or HasFlagFast() extension methods instead.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0015AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0015AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply the Bluehill.EnumExtensionsAttribute to the enumeration and use &apos;{0}&apos; method과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0015AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0015AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply the Bluehill.EnumExtensionsAttribute to the enumeration and use ToStringFast() or HasFlagFast()과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BH0015AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0015AnalyzerTitle", resourceCulture);
            }
        }
    }
}
