//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluehill.Analyzers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bluehill.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BH0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0001AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string BH0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string BH0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0001AnalyzerTitle", resourceCulture);
            }
        }
        
        internal static string BH0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0002AnalyzerDescription", resourceCulture);
            }
        }
        
        internal static string BH0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        internal static string BH0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0002AnalyzerTitle", resourceCulture);
            }
        }
    }
}
