//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluehill.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bluehill.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes without derived types should be sealed..
        /// </summary>
        internal static string BH0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No types are derived from class &apos;{0}&apos;.
        /// </summary>
        internal static string BH0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes without derived types should be sealed.
        /// </summary>
        internal static string BH0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should be at the top of the type definition..
        /// </summary>
        internal static string BH0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not at the top of the type definition.
        /// </summary>
        internal static string BH0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should be at the top of the type definition.
        /// </summary>
        internal static string BH0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0002AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameters of the primary constructor must not be reassigned..
        /// </summary>
        internal static string BH0003AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0003AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been reassigned.
        /// </summary>
        internal static string BH0003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0003AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibit reassignment of primary constructor parameters.
        /// </summary>
        internal static string BH0003AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0003AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() must be implemented explicitly..
        /// </summary>
        internal static string BH0004AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0004AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() is not explicitly implemented.
        /// </summary>
        internal static string BH0004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0004AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() must be explicitly implemented.
        /// </summary>
        internal static string BH0004AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0004AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() must return null, and must not be abstract or throw exceptions..
        /// </summary>
        internal static string BH0005AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0005AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() does not return null.
        /// </summary>
        internal static string BH0005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0005AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() must return null.
        /// </summary>
        internal static string BH0005AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0005AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IXmlSerializable.GetSchema() should never be called..
        /// </summary>
        internal static string BH0006AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0006AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling IXmlSerializable.GetSchema().
        /// </summary>
        internal static string BH0006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0006AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never call IXmlSerializable.GetSchema().
        /// </summary>
        internal static string BH0006AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0006AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to use System.Threading.Lock instead of System.Object for locking..
        /// </summary>
        internal static string BH0007AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0007AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System.Threading.Lock.
        /// </summary>
        internal static string BH0007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0007AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer System.Threading.Lock over System.Object.
        /// </summary>
        internal static string BH0007AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0007AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The negated pattern should not be used repeatedly..
        /// </summary>
        internal static string BH0008AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0008AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;not&apos; only once or not at all.
        /// </summary>
        internal static string BH0008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0008AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t repeat negative patterns.
        /// </summary>
        internal static string BH0008AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0008AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integers and Decimal should never be divided by the constant 0. This may cause a DividedByZeroException..
        /// </summary>
        internal static string BH0009AnalyzerDescription {
            get {
                return ResourceManager.GetString("BH0009AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividing by constant 0.
        /// </summary>
        internal static string BH0009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("BH0009AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integers and Decimal should never be divided by the constant 0.
        /// </summary>
        internal static string BH0009AnalyzerTitle {
            get {
                return ResourceManager.GetString("BH0009AnalyzerTitle", resourceCulture);
            }
        }
    }
}
